package com.crossa.androiddemo

import android.content.Context
import org.json.JSONObject

object CrossaAssetReader {
    fun read(context: Context): ScenarioResult {
        val json = context.assets.open("crossa_metrics.json")
            .bufferedReader()
            .use { JSONObject(it.readText()) }
        val firstPostJson = json.optJSONObject("firstPost")
        val firstPost = firstPostJson?.let {
            Post(
                userId = it.optInt("userId"),
                id = it.optInt("id"),
                title = it.optString("title"),
                body = it.optString("body")
            )
        }
        val timings = json.optJSONArray("timingsMs")?.let { array ->
            buildList {
                for (index in 0 until array.length()) {
                    add(array.optLong(index))
                }
            }
        }.orEmpty()
        val headersJson = json.optJSONObject("requestHeaders")
        val headers = buildMap {
            if (headersJson != null) {
                val names = headersJson.keys()
                while (names.hasNext()) {
                    val name = names.next()
                    put(name, headersJson.optString(name))
                }
            }
        }

        return ScenarioResult(
            name = json.optString("scenario", "Crossa CLI"),
            requestUrl = json.optString("requestUrl"),
            requestCount = json.optInt("requestCount"),
            successCount = json.optInt("successCount"),
            totalMs = json.optLong("totalMs"),
            averageMs = json.optDouble("averageMs"),
            minMs = json.optLong("minMs"),
            maxMs = json.optLong("maxMs"),
            postCount = json.optInt("postCount"),
            firstPost = firstPost,
            timingsMs = timings,
            requestHeaders = headers,
            responseInfo = "Generated by Crossa CLI Gradle task",
            responsePreview = json.optString("responsePreview")
        )
    }
}
